import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      { <Script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossOrigin="anonymous" />}
      <link href="https://hangeul.pstatic.net/hangeul_static/css/maru-buri.css" rel="stylesheet"></link>
      <style> {`
          body {
            font-family: 'MaruBuri';
            margin-top: 100px;
            margin-left: 200px;
            margin-right: 200px;
          }
        `}</style>
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        {children}
      </body>
    </html>
  );
}
